services:
  homeassistant:
    container_name: homeassistant
    build: .
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
volumes:
  homeassistant: