services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --cleanup
    environment:
      - WATCHTOWER_SCHEDULE=0 4 * * *
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"